baseURL: "https://dongheechoi.github.io"
title: "Donghee Choi"
theme: "PaperMod"

pagination:
  pagerSize: 5

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  editPost:
    disabled: true
    hideFooter: true
  homeInfoParams:
    Title: "PNU-CLinK Lab"
    Content: |
      Computational Linguistics & Knowledge (CLinK) Lab
      Pusan National University, Busan, South Korea

      <p><strong><a href="https://sites.google.com/view/pnu-clink" target="_blank">Visit the lab website</a></strong></p>

  disableHomePageList: true

  socialIcons:
    - name: email
      url: "mailto:dchoi@pusan.ac.kr"
    - name: github
      url: "https://github.com/dongheechoi"
    - name: linkedin
      url: "https://www.linkedin.com/in/dongheechoi/"
    - name: x
      url: "https://x.com/iamdongheechoi"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=iR40DeMAAAAJ"

menu:
  main:
    - name: "Research"
      url: "/research/"
      weight: 1
    - name: "Lab Website"
      url: "https://sites.google.com/view/pnu-clink"
      weight: 2
